#:schema node_modules/wrangler/config-schema.json
name = "supermemory-web"
compatibility_date = "2024-09-23"
pages_build_output_dir = "./build/client"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "METADATA_KV"
id = "d8e137aaf585428d87f6815b356d7c44"
preview_id = "f17c6965280342f18de672b304faf8d0"

[[kv_namespaces]]
binding = "ENCRYPTED_TOKENS"
id = "f2660879f3414290a748cad4bec31043"
preview_id = "5cc6a06ffa354019aedacd5201b20786"

[[r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "supermemory-images"


[[hyperdrive]]
binding = "HYPERDRIVE"
id = "169f9429db4840dca58e7c8f73636494"
localConnectionString = "postgresql://postgres:postgres@localhost:5432/supermemory"

[placement]
mode = "smart"