version: "3.8"

services:
  db:
    build: .
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=supermemory
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres # Lütfen bu şifreyi daha güvenli bir şifre ile değiştirin.
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
