name = "supermemory-backend"
main = "src/index.tsx"
compatibility_date = "2024-10-11"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = "./public/"
binding = "ASSETS"


[observability]
enabled = true

[placement]
mode = "smart"

[ai]
binding = "AI"

[[workflows]]
name = "workflows-starter"
binding = "MY_WORKFLOW"
class_name = "ContentWorkflow"


[[kv_namespaces]]
binding= "MD_CACHE"
id = "179877c7b9724f9e85cbdd0badd2312e"
preview_id = "f2628aa93f964982a051af6ea7e791e7"

[[kv_namespaces]]
binding = "ENCRYPTED_TOKENS"
id = "f2660879f3414290a748cad4bec31043"
preview_id = "5cc6a06ffa354019aedacd5201b20786"

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "169f9429db4840dca58e7c8f73636494"
localConnectionString = "postgresql://postgres:postgres@localhost:5432/supermemory"

[[unsafe.bindings]]
name = "EMAIL_LIMITER"
type = "ratelimit"
namespace_id = "2114284"
simple = { limit = 1, period = 60 }

tail_consumers = [{service = "supermemory-backend-tail"}]

[[durable_objects.bindings]]
name = "RATE_LIMITER"
class_name = "DurableObjectRateLimiter"

[[migrations]]
tag = "v1"
new_classes = ["DurableObjectRateLimiter"]